openapi: 3.0.1
info:
  title: "Inference API Schema"
  description: 'Inference API Schema'
  version: "1.0"
servers:
  - url: TBD
paths:
  /pdf/inference/summarize:
    post:
      operationId: inferPdfData
      summary: |
        DocMaestroEngine makes the call to inference service with the pdf bytes in the request. The service then extract relevant information from a LLM. This process occurs asynchronously.
      requestBody:
        description: Contains PDF content       
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PdfInferenceRequest'
      responses:
        202:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        400:
          description: Bad data was posted to the endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        401:
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        405:
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
      x-codegen-request-body-name: body  
  /pdf/inference/outcome/{request_id}:
    get:
      operationId: getInferenceResponse
      summary: Gets the response of the inference summary
      parameters: 
        - name : "request_id"
          in  : "path"
          description : "request_id generated by POST API"
          required: true
          schema :
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceResponse'
        400:
          description: Bad data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        401:
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        405:
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
      x-codegen-request-body-name: body
  /pdf/inference/ocr/{request_id}:
    get:
      operationId: getOcrInferenceResponse
      summary: Gets the response of the inference summary
      parameters: 
        - name : "request_id"
          in  : "path"
          description : "request_id generated by POST API"
          required: true
          schema :
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PdfTextExtractJson'
        400:
          description: Bad data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        401:
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        405:
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        415:
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
      x-codegen-request-body-name: body
components:
  schemas:
    PdfInferenceRequest:
      type: object
      required: [pdf_data, queries, model_id]
      properties:
        pdf_data :
          type: string
          description: base64 encoded pdf string
        model_id :
          type: string
          description: Which foundational model should bedrock use to evaluate the request
        queries :
          type: array
          description: List of questions to ask the AI model
          items:
            $ref: '#/components/schemas/Query'
        generic_info:
          type: array
          description: Array of key-value pairs to store additional information
          items: 
            $ref: '#/components/schemas/GenericInfo'
    Query:
      type: object
      required: [top_p, question]
      properties:
        max_tokens:
          type: integer 
          description: the max number of tokens allowed in the response. If this value is left blank it is defualted to the model's max_token number.          
        temperature:
          type: number
        top_p:
          type: number
        question:
          type: string
        question_key:
          type: string
        mime_type:
          type: string
          enum: 
            - application/xml
            - application/json
            - text/plain
        extract_info:
          $ref: '#/components/schemas/ExtractInfo'
    InferenceResponse:
      type: object
      properties: 
        status:
          type: string
          enum:
            - IN_PROGRESS
            - FAILED
            - SUCCESS
            - UNKNOWN
        request_id: 
          type: string
          description: generated id for the request.
        inferences:
          type: array
          items:
            $ref: '#/components/schemas/InferenceAnswer'
    InferenceAnswer:
      type: object
      properties:
        query:
          type: string  
        answer:
          type: string
        question_key:
          type: string
        mime_type:
          type: string
          enum: 
            - application/xml
            - application/json
            - text/plain          
    GenericInfo:
      type: object
      properties:
        key:
          type: string  
        value:
          type: object
        description:
          type: string
    APIResponse:
      type: object
      properties:
        status:
          type: string  
        message:
          type: string
        request_id :
          type: string
          description: generated id for the request. This has to maintained by the caller to get the results.
    ExtractInfo:
      type: object
      required: [extract_fields]
      properties: 
        extract_fields:
          type: array
          description: array of fields to capture in the response
          items:
            $ref: '#/components/schemas/ExtractionField'
    BoundingBox:
      type: object
      properties:
         column_threshold:
           type: number
           description: a value from 0 to 1 to control where the vertical column is that seperates LHS from RHS
         header_threshold:
           type: number
           description: a value from 0 to 1 to control where the header on a particular pages ends and the content begins
         footer_threshold:
           type: number
           description: a value from 0 to 1 to control where the content of a page ends and the footer begins
         indent_threshold:
           type: number
           description: a value from 0 to 1 to control how much a value is indented if it continues to a new line
         height_tolerance:
           type: number
           description: a value from 0 to 1 to control how much a value is indented if it continues to a new line
    ExtractionField:
      type: object
      required: [input_field_name, output_field_name]
      properties:
        lower_page:
          type: int
          description: The lowest page value the field could appear
        upper_page:
          type: int
          description: The highest page value the field could appear
        input_field_name:
          type: string
        bounding_box:
          $ref: '#/components/schemas/BoundingBox'
        output_field_name:
          type: string
        preceding_field_label:
          type: string
        subsequent_field_label:
          type: string
        enum_traits:
          $ref: '#/components/schemas/EnumTrait'
    EnumTrait:
      type: object
      properties: 
        answers:
          type: array
          items: 
            type: string
            description: List of possible values for a field.
        regex:
          type: string
          description: regex expression for what the possible value is.
