spring.jpa.hibernate.ddl-auto=none
#spring.hibernate.jdbc.fetch_size=50
spring.jpa.open-in-view=false

spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.minimum-idle=25
spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.auto-commit=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mustache.check-template-location=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/New_York

spring.application.name=inference
info.maestro.API_VERSION = v1
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
management.info.build.enabled=true
management.info.git.enabled=true
management.security.enabled=false 

maestro.gp.po.models=us.anthropic.claude-sonnet-4-6
maestro.inference.config.temp=0.0
maestro.inference.config.topP=0.999
maestro.inference.config.retry=3
maestro.inference.config.retryDelay=2000
maestro.inference.config.retryMultiply=1.2
maestro.inference.config.idpS3Bucket=gp-idp-dev
maestro.inference.guardrail.enabled=false
maestro.inference.guardrail.id=mp8yw9l454gp
maestro.inference.guardrail.version=4
maestro.inference.config.textractCompletedJobStatus=SUCCEEDED,FAILED
maestro.inference.config.tokenLimit=500000
maestro.inference.config.maxWait=7200000
maestro.inference.config.textract.throttle.sleepInterval=20000
maestro.inference.config.textract.throttle.getDocTextLimit=5
maestro.inference.config.textract.throttle.startDocTextLimit=5
maestro.inference.config.textractShortSleepInterval=500
maestro.inference.config.textractSleepInterval=20000
spring.jta.enabled=false
management.security.enabled=false

debug=true

maestro.system.local=false
maestro.system.roleArn=arn:aws:iam::837966179256:role/InferenceRole
maestro.system.poll.interval=3000
maestro.gp.po.size_limit=4000000
maestro.system.readTimeout=10
