------------------------ START  ---------------------------------------------
CREATE TABLE ENUM_INFERENCE_ANSWER_MIME_TYPE(
	VALUE 				VARCHAR2(64 BYTE),
	DESCRIPTION 		VARCHAR2(256),
	REPORT_LABEL 		VARCHAR2(64),
	SCOPE 				VARCHAR2(128),
	CREATED_BY 			VARCHAR2(80),
	CREATE_TS 			DATE,
	UPDATED_BY 			VARCHAR2(80),
	UPDATE_TS 			DATE,
	ORDER_BY_DEFAULT 	NUMBER(10,0),
	EFFECTIVE_START_DATE DATE,
	EFFECTIVE_END_DATE 	DATE,
	CONSTRAINT ENUM_INFERENCE_ANSWER_MIME_TYPE_PK PRIMARY KEY (VALUE)
);

CREATE OR REPLACE PUBLIC SYNONYM ENUM_INFERENCE_ANSWER_MIME_TYPE FOR ENUM_INFERENCE_ANSWER_MIME_TYPE;
GRANT INSERT, SELECT, UPDATE ON ENUM_INFERENCE_ANSWER_MIME_TYPE TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENUM_INFERENCE_ANSWER_MIME_TYPE TO EB_OLTP_SIUD;
GRANT SELECT ON ENUM_INFERENCE_ANSWER_MIME_TYPE TO EB_READ_ONLY;

INSERT INTO ENUM_INFERENCE_ANSWER_MIME_TYPE(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('application/xml', 'application/xml','application/xml', 'GP-100-53077', TRUNC(SYSDATE), 1, TRUNC(SYSDATE));

INSERT INTO ENUM_INFERENCE_ANSWER_MIME_TYPE(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('application/json', 'application/json','application/json', 'GP-100-53077', TRUNC(SYSDATE), 2, TRUNC(SYSDATE));

INSERT INTO ENUM_INFERENCE_ANSWER_MIME_TYPE(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('text/plain', 'text/plain','text/plain', 'GP-100-53077', TRUNC(SYSDATE), 3, TRUNC(SYSDATE));

CREATE TABLE ENUM_INFERENCE_STATUS(
	VALUE 				VARCHAR2(64 BYTE),
	DESCRIPTION 		VARCHAR2(256),
	REPORT_LABEL 		VARCHAR2(64),
	SCOPE 				VARCHAR2(128),
	CREATED_BY 			VARCHAR2(80),
	CREATE_TS 			DATE,
	UPDATED_BY 			VARCHAR2(80),
	UPDATE_TS 			DATE,
	ORDER_BY_DEFAULT 	NUMBER(10,0),
	EFFECTIVE_START_DATE DATE,
	EFFECTIVE_END_DATE 	DATE,
	CONSTRAINT ENUM_INFERENCE_STATUS_PK PRIMARY KEY (VALUE)
);

CREATE OR REPLACE PUBLIC SYNONYM ENUM_INFERENCE_STATUS FOR ENUM_INFERENCE_STATUS;
GRANT INSERT, SELECT, UPDATE ON ENUM_INFERENCE_STATUS TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENUM_INFERENCE_STATUS TO EB_OLTP_SIUD;
GRANT SELECT ON ENUM_INFERENCE_STATUS TO EB_READ_ONLY;

INSERT INTO ENUM_INFERENCE_STATUS(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('IN_PROGRESS', 'IN_PROGRESS','IN_PROGRESS', 'GP-100-53077', TRUNC(SYSDATE), 1, TRUNC(SYSDATE));

INSERT INTO ENUM_INFERENCE_STATUS(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('FAILED', 'FAILED','FAILED', 'GP-100-53077', TRUNC(SYSDATE), 2, TRUNC(SYSDATE));

INSERT INTO ENUM_INFERENCE_STATUS(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('SUCCESS', 'SUCCESS','SUCCESS', 'GP-100-53077', TRUNC(SYSDATE), 3, TRUNC(SYSDATE));

INSERT INTO ENUM_INFERENCE_STATUS(VALUE, DESCRIPTION, REPORT_LABEL, CREATED_BY, CREATE_TS, ORDER_BY_DEFAULT, EFFECTIVE_START_DATE)
VALUES('UNKNOWN', 'UNKNOWN','UNKNOWN', 'GP-100-53077', TRUNC(SYSDATE), 4, TRUNC(SYSDATE));

COMMIT;

CREATE TABLE INFERENCE_RESPONSE (
	INFERENCE_RESPONSE_ID 	NUMBER(18,0),
	REQUEST_ID              VARCHAR2(64),
	STATUS_CD               VARCHAR2(64),
	CREATED_BY       		VARCHAR2(32),
	CREATE_TS        		DATE,
	UPDATED_BY       		VARCHAR2(32),
	UPDATE_TS        		DATE,
	CONSTRAINT INFERENCE_RESPONSE_PK PRIMARY KEY (INFERENCE_RESPONSE_ID)
);

COMMIT;

ALTER TABLE INFERENCE_RESPONSE ADD CONSTRAINT INFERENCE_RESPONSE_FK1
   FOREIGN KEY (STATUS_CD)
   REFERENCES ENUM_INFERENCE_STATUS(VALUE);
CREATE OR REPLACE PUBLIC SYNONYM INFERENCE_RESPONSE FOR INFERENCE_RESPONSE;
GRANT INSERT, SELECT, UPDATE ON INFERENCE_RESPONSE TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON INFERENCE_RESPONSE TO EB_OLTP_SIUD;
GRANT SELECT ON INFERENCE_RESPONSE TO EB_READ_ONLY;

CREATE SEQUENCE "SEQ_INFERENCE_RESPONSE_ID" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;		
INSERT INTO SEQUENCE_MAP (SEQUENCE_MAP_ID, SEQUENCE_NAME) VALUES ('INFERENCE_RESPONSE.INFERENCE_RESPONSE_ID', 'SEQ_INFERENCE_RESPONSE_ID');

COMMIT;

CREATE TABLE INFERENCE_RESPONSE_HIST (
    INFERENCE_RESPONSE_HIST_ID NUMBER(18,0),
	INFERENCE_RESPONSE_ID 	NUMBER(18,0),
	REQUEST_ID              VARCHAR2(64),
	STATUS_CD               VARCHAR2(64),
	CREATED_BY       		VARCHAR2(32),
	CREATE_TS        		DATE,
	UPDATED_BY       		VARCHAR2(32),
	UPDATE_TS        		DATE,
	CONSTRAINT INFERENCE_RESPONSE_HIST_PK PRIMARY KEY (INFERENCE_RESPONSE_HIST_ID)
);

COMMIT;

ALTER TABLE INFERENCE_RESPONSE_HIST ADD CONSTRAINT INFERENCE_RESPONSE_HIST_FK1
   FOREIGN KEY (STATUS_CD)
   REFERENCES ENUM_INFERENCE_STATUS(VALUE);
ALTER TABLE INFERENCE_RESPONSE_HIST ADD CONSTRAINT INFERENCE_RESPONSE_HIST_FK2
   FOREIGN KEY (INFERENCE_RESPONSE_ID)
   REFERENCES INFERENCE_RESPONSE(INFERENCE_RESPONSE_ID);
CREATE OR REPLACE PUBLIC SYNONYM INFERENCE_RESPONSE_HIST FOR INFERENCE_RESPONSE_HIST;
GRANT INSERT, SELECT, UPDATE ON INFERENCE_RESPONSE_HIST TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON INFERENCE_RESPONSE_HIST TO EB_OLTP_SIUD;
GRANT SELECT ON INFERENCE_RESPONSE_HIST TO EB_READ_ONLY;

CREATE SEQUENCE "SEQ_INFERENCE_RESPONSE_HIST_ID" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;		
INSERT INTO SEQUENCE_MAP (SEQUENCE_MAP_ID, SEQUENCE_NAME) VALUES ('INFERENCE_RESPONSE_HIST.INFERENCE_RESPONSE_HIST_ID', 'SEQ_INFERENCE_RESPONSE_HIST_ID');

CREATE OR REPLACE TRIGGER "INFERENCE_RESPONSE_HIST_INSERT" 
AFTER INSERT
ON INFERENCE_RESPONSE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO INFERENCE_RESPONSE_HIST
	(
		INFERENCE_RESPONSE_HIST_ID,
		INFERENCE_RESPONSE_ID,
		REQUEST_ID,
		STATUS_CD,
		CREATED_BY,
		CREATE_TS,
		UPDATED_BY,
		UPDATE_TS
	)
	VALUES
	(
		SEQ_INFERENCE_RESPONSE_HIST_ID.NEXTVAL,
		:NEW.INFERENCE_RESPONSE_ID,
		:NEW.REQUEST_ID,
		:NEW.STATUS_CD,
 		:NEW.CREATED_BY,
		:NEW.CREATE_TS,
		:NEW.UPDATED_BY,
		:NEW.UPDATE_TS
	);
	EXCEPTION
	WHEN OTHERS THEN
	RAISE;
END INFERENCE_RESPONSE_HIST_INSERT;

ALTER TRIGGER "INFERENCE_RESPONSE_HIST_INSERT" ENABLE;

COMMIT;

CREATE TABLE INFERENCE_ANSWER
(
	INFERENCE_ANSWER_ID 	NUMBER(18,0),
	INFERENCE_RESPONSE_ID 	NUMBER(18,0),
	QUERY            		CLOB,
	ANSWER            		VARCHAR2(32767),
	MIME_TYPE        		VARCHAR2(32),
	CREATED_BY       		VARCHAR2(32),
	CREATE_TS        		DATE,
	UPDATED_BY       		VARCHAR2(32),
	UPDATE_TS        		DATE,
	CONSTRAINT INFERENCE_ANSWER_PK PRIMARY KEY (INFERENCE_ANSWER_ID)
);

COMMIT;

ALTER TABLE INFERENCE_ANSWER ADD CONSTRAINT INFERENCE_ANSWER_FK1
   FOREIGN KEY (INFERENCE_RESPONSE_ID)
   REFERENCES INFERENCE_RESPONSE(INFERENCE_RESPONSE_ID);
ALTER TABLE INFERENCE_ANSWER ADD CONSTRAINT INFERENCE_ANSWER_FK2
   FOREIGN KEY (MIME_TYPE)
   REFERENCES ENUM_INFERENCE_ANSWER_MIME_TYPE(VALUE);
CREATE OR REPLACE PUBLIC SYNONYM INFERENCE_ANSWER FOR INFERENCE_ANSWER;
GRANT INSERT, SELECT, UPDATE ON INFERENCE_ANSWER TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON INFERENCE_ANSWER TO EB_OLTP_SIUD;
GRANT SELECT ON INFERENCE_ANSWER TO EB_READ_ONLY;

CREATE SEQUENCE "SEQ_INFERENCE_ANSWER_ID" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;		
INSERT INTO SEQUENCE_MAP (SEQUENCE_MAP_ID, SEQUENCE_NAME) VALUES ('INFERENCE_ANSWER.INFERENCE_ANSWER_ID', 'SEQ_INFERENCE_ANSWER_ID');

COMMIT;


------------------------ END  GP-100 ---------------------------------------------

----------------------------------------- START GP-100 -----------------------------------
ALTER TABLE INFERENCE_ANSWER ADD QUESTION_KEY VARCHAR2(256);
COMMIT;
----------------------------------------- END GP-100 -------------------------------------
----------------------------------------- GP-100 START -----------------------------------
CREATE OR REPLACE TRIGGER INFERENCE_RESPONSE_HIST_UPDATE
 AFTER UPDATE
OF
	INFERENCE_RESPONSE_ID,
	REQUEST_ID,
	STATUS_CD,
	CREATED_BY,
	CREATE_TS,
	UPDATED_BY,
	UPDATE_TS	
	ON INFERENCE_RESPONSE 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
       INSERT INTO INFERENCE_RESPONSE_HIST
	     (INFERENCE_RESPONSE_HIST_ID, 
		 INFERENCE_RESPONSE_ID,
		 REQUEST_ID, 
		 STATUS_CD,  
		 CREATED_BY, 
		 CREATE_TS, 
         UPDATED_BY, 
		 UPDATE_TS)
	 VALUES
	   (SEQ_INFERENCE_RESPONSE_HIST_ID.nextval, 
	    :NEW.INFERENCE_RESPONSE_ID, 
	    :NEW.REQUEST_ID, 
	    :NEW.STATUS_CD, 
	    :NEW.CREATED_BY, 
		:NEW.CREATE_TS,  
		:NEW.UPDATED_BY, 
		:NEW.UPDATE_TS);
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END INFERENCE_RESPONSE_HIST_UPDATE;
/

ALTER TRIGGER "INFERENCE_RESPONSE_HIST_UPDATE" ENABLE;

COMMIT;
----------------------------------------- END GP-100 -------------------------------------------
------------------------------------------------ START GP-100 --------------------------------------------------------------
CREATE TABLE PDF_TEXT_EXTRACT_JSON
(
  PDF_TEXT_EXTRACT_JSON_ID NUMBER(18),
  REQUEST_ID               VARCHAR2(256 BYTE),
  JSON					   CLOB,
  RAW_JSON                 CLOB,
  CREATED_BY               VARCHAR2(50 BYTE),
  CREATE_TS                DATE,
  UPDATED_BY               VARCHAR2(50 BYTE),
  UPDATE_TS                DATE
);


CREATE UNIQUE INDEX IDX_PDF_TEXT_EXTRACT_JSON_DOC_ID ON PDF_TEXT_EXTRACT_JSON (PDF_TEXT_EXTRACT_JSON_ID);

CREATE UNIQUE INDEX PDF_TEXT_EXTRACT_JSON_PK ON PDF_TEXT_EXTRACT_JSON (REQUEST_ID);

ALTER TABLE PDF_TEXT_EXTRACT_JSON ADD PRIMARY KEY (PDF_TEXT_EXTRACT_JSON_ID);
  
INSERT INTO SEQUENCE_MAP
   (SEQUENCE_MAP_ID, SEQUENCE_NAME)
VALUES
   ('PDF_TEXT_EXTRACT_JSON.PDF_TEXT_EXTRACT_JSON_ID', 'SEQ_PDF_TEXT_EXTRACT_JSON_ID');
   
CREATE SEQUENCE SEQ_PDF_TEXT_EXTRACT_JSON_ID
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE PUBLIC SYNONYM PDF_TEXT_EXTRACT_JSON FOR PDF_TEXT_EXTRACT_JSON;
GRANT INSERT, SELECT, UPDATE ON PDF_TEXT_EXTRACT_JSON TO EB_OLTP_SIU;
GRANT DELETE, INSERT, SELECT, UPDATE ON PDF_TEXT_EXTRACT_JSON TO EB_OLTP_SIUD;
GRANT SELECT ON PDF_TEXT_EXTRACT_JSON TO EB_READ_ONLY;

COMMIT;


------------------------------------------------ END GP-100 ----------------------------------------------------------------
-------------------------------------- START GP-100 -------------------------------------------------
ALTER TABLE INFERENCE_ANSWER ADD (INPUT_TOKEN_COUNT NUMBER(10,0));
ALTER TABLE INFERENCE_ANSWER ADD (OUTPUT_TOKEN_COUNT NUMBER(10,0));

COMMIT;
------------------------------------- END GP-100 -----------------------------------------------------
